//Project Euler Problem 2
//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <stdio.h>

using namespace std;

int main(int argc, char const *argv[])
{
	long a = 1;
	long b = 0;
	long c = 0;
	long ans = 0;

	do{

		//printf("a: %i", a);
		//printf(" b: %i", b);
		

		c =  a + b;
		a = b;
		b = c;

		//printf(" c: %i \n", c); 		

		if(c % 2 == 0)
		{
			ans += c;
		}
	}while(b < 4000000);

	printf("Answer: %i\n", ans);

	return 0;
}